### ISSUE TITLE
error: Cannot fetch titan/aosp/external/expat (GitError: titan/aosp/external/expat update-ref: fatal: 396a0d1d7fbdfd1384f29f3af959834bc90b4e0f^0: not a valid SHA1

### ISSUE THREAD

**Issue by vksagar23** [seL4/seL4#151]
when i tried to do repo sync getting below error.
error: Cannot fetch titan/aosp/external/expat (GitError: titan/aosp/external/expat update-ref: fatal: 396a0d1d7fbdfd1384f29f3af959834bc90b4e0f^0: not a va                                                                                   lid SHA1
)
Exception in thread Thread-20:
Traceback (most recent call last):
--
GitError: titan/aosp/external/expat update-ref: fatal: 396a0d1d7fbdfd1384f29f3af959834bc90b4e0f^0: not a valid SHA1

error: Cannot fetch bsp/Intel/vendor/intel/tools/itt (GitError: bsp/Intel/vendor/intel/tools/itt update-ref: fatal: 74323d6c1e22ff05d6f411c18a3ecd15c5b508                                                                                   5a^0: not a valid SHA1
)
Exception in thread Thread-23:
Traceback (most recent call last):

**Comment by vksagar23** [comment]
[repo_sync1.log](https://github.com/seL4/seL4/files/3583517/repo_sync1.log)

**Comment by wom-bat** [comment]
I don't recognise that URI.  Doesn't look like it's from the  seL4 repository ... can you please be a little more explicit as to what you did to see the error?  Give the full command that failed, and the repo init command you used before the sync call.

**Comment by vksagar23** [comment]
repo init -u ssh://$USER@androidhub.harman.com:29418/android/manifest -b titan_platform_oCar -m titan_platform_oCar_master.xml --repo-url=ssh://androidhub.harman.com:29418/harman/repo --repo-branch=harman-stable --no-repo-verify

repo init is fine no issues.

then i tried to run "repo sync"  getting below error.
error: Cannot fetch bsp/Intel/vendor/intel/tools/itt (GitError: bsp/Intel/vendor/intel/tools/itt update-ref: fatal: 74323d6c1e22ff05d6f411c18a3ecd15c5b5085a^0: not a valid SHA1
)
Fetching project titan/aosp/system/gatekeeper
Skipped fetching project titan/aosp/prebuilts/abi-dumps/ndk (already have persistent ref)
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/subcmds/sync.py", line 289, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/subcmds/sync.py", line 334, in _FetchHelper
    prune=opt.prune)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 1323, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2462, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2474, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2784, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2858, in runner
    (self._project.name, name, p.stderr))
GitError: bsp/Intel/vendor/intel/tools/itt update-ref: fatal: 74323d6c1e22ff05d6f411c18a3ecd15c5b5085a^0: not a valid SHA1


error: Cannot fetch titan/aosp/external/expat (GitError: titan/aosp/external/expat update-ref: fatal: 396a0d1d7fbdfd1384f29f3af959834bc90b4e0f^0: not a valid SHA1
)
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/subcmds/sync.py", line 289, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/subcmds/sync.py", line 334, in _FetchHelper
    prune=opt.prune)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 1323, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2462, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2474, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2784, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/iconnectivit/workspace/ocar/.repo/repo/project.py", line 2858, in runner
    (self._project.name, name, p.stderr))
GitError: titan/aosp/external/expat update-ref: fatal: 396a0d1d7fbdfd1384f29f3af959834bc90b4e0f^0: not a valid SHA1

**Comment by wom-bat** [comment]
The URI you are using has nothing to do with seL4.  Closing this issue as irrelevant to this repository.
