### ISSUE TITLE
syscall_stub_gen.py ... --word-size 32 ... invocation fails

### ISSUE THREAD

**Issue by alex-ab** [seL4/seL4#29]
```
python sel4/libsel4/tools/syscall_stub_gen.py --buffer -a ia32 --word-size 32 -o ...

Traceback (most recent call last):
  File ".../libsel4/tools/syscall_stub_gen.py", line 821, in <module>
    sys.exit(main())
  File ".../libsel4/tools/syscall_stub_gen.py", line 817, in main
    generate_stub_file(args.arch, wordsize, args.files, args.output, args.buffer)
  File ".../libsel4/tools/syscall_stub_gen.py", line 725, in generate_stub_file
    result.append("assert_size_correct(%s, %d);" % (x.name, x.native_size_bits / 8))
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by alex-ab** [comment]
Added a commit which fixes the issue for us.
