### ISSUE TITLE
MOD_PYTHON error on http://sel4.systems

### ISSUE THREAD

**Issue by manoelhc** [seL4/seL4#80]
sel4.systems is not reachable. Probably module lxml is not installed properly.

```MOD_PYTHON ERROR

ProcessId:      3936
Interpreter:    'sel4.systems.keg.ertos.in.nicta.com.au'

ServerName:     'sel4.systems.keg.ertos.in.nicta.com.au'
DocumentRoot:   '/var/www/seL4/content'

URI:            '/home.pml'
Location:       '/home.pml'
Directory:      None
Filename:       '/var/www/seL4/content/home.pml'
PathInfo:       None

Phase:          'PythonHandler'
Handler:        'ertos'

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 1202, in _process_target
    module = import_module(module_name, path=path)

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 304, in import_module
    return __import__(module_name, {}, {}, ['*'])

  File "/var/www/seL4/code/ertos.py", line 5, in <module>
    from lxml import etree

ImportError: No module named lxml
```

**Comment by wom-bat** [comment]
Fixed.
